version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    # command: ./docker-entrypoint.sh
    # ports:
    #   - "8000:8000"

    volumes:
      - static_volume:/home/app/beckend/staticfiles
      - media_volume:/home/app/beckend/media
      - gunicorn_socket:/var/run

    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=production
    
    depends_on:
      - redis
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=adora_db
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/beckend/staticfiles
      - gunicorn_socket:/var/run
    ports:
      - 80:80
    depends_on:
      - backend


volumes:
  postgres_data:
  media_volume:
  static_volume:
  gunicorn_socket:

