# version: '3.8'

services:
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    # image: adora-app
    image: adora-backend
    volumes:
      - static_volume:/home/app/backend/core/static
      - media_volume:/home/app/backend/media
      - gunicorn_socket:/var/run
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=production
    depends_on:
      - redis_master
      - redis_replica
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=adora_db
    ports:
      - 5432:5432
    restart: unless-stopped

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   restart: always

  redis_master:
    image: "redis:alpine"
    container_name: redis_master
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
    command: redis-server --requirepass "1234" # Optional: If you want to set a password
    restart: always

  redis_replica:
    image: "redis:alpine"
    container_name: redis_replica
    environment:
      - REDIS_MASTER_HOST=redis_master
      - REDIS_MASTER_PORT=6379
    command: redis-server --slaveof redis_master 6379 --requirepass "1234" --masterauth "1234" # Optional: if using password
    ports:
      - "6380:6379" # Map to a different port to avoid conflict
    restart: always

  nginx:
    build: ./nginx
    # image: adora-nginx
    volumes:
      - static_volume:/home/app/backend/core/static
      - media_volume:/home/app/backend/media
      - gunicorn_socket:/var/run
      - ./ssl:/etc/nginx/ssl
      - flower_static:/usr/share/nginx/flower_static # Mount the shared volume here
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always

  celery:
    # build:
    # context: .
    # dockerfile: Dockerfile.prod
    image: adora-backend
    user: "1000:1000"

    entrypoint: ./docker-entrypoint-celery-worker.sh
    # volumes:
    #   - .:/home/app/backend/
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=production
    depends_on:
      - redis_master
      - redis_replica
      - db
      - backend

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   image: adora-app
  #   entrypoint: ./docker-entrypoint-celery-beat.sh
  #   # volumes:
  #   #   - .:/home/app/backend/
  #   env_file:
  #     - ./.env.dev
  # environment:
  #   - DJANGO_ENV=production
  #   depends_on:
  #     - redis
  #     - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # image: adora-backend
    entrypoint: ./docker-entrypoint-celery-flower.sh
    volumes:
      - static_volume:/home/app/backend/core/static
      - flower_static:/usr/local/lib/python3.11/site-packages/flower/static # Share the volume with Nginx

    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=production
      - REDIS_PASSWORD="1234"
    ports:
      - 5557:5555
    depends_on:
      - redis_master
      - redis_replica
      - db

volumes:
  postgres_data:
  media_volume:
  static_volume:
  gunicorn_socket:
  redis_master_data:
  flower_static:
