version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.prod

    # image: backend:1.0
    volumes:
      - static_volume:/home/app/backend/core/static
      - media_volume:/home/app/backend/media
      - gunicorn_socket:/var/run
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=production
    depends_on:
      - redis
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=adora_db
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  nginx:
    build: ./nginx
    # image: nginx:1.0
    volumes:
      - static_volume:/home/app/backend/core/static
      - media_volume:/home/app/backend/media
      - gunicorn_socket:/var/run
      - ./ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 433:433
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  media_volume:
  static_volume:
  gunicorn_socket:

