version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: adora-app
    # command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

    environment:
      - DJANGO_ENV=development

    volumes:
      - .:/home/app/backend/
      - static_volume_lo:/home/app/beckend/core/staticfiles
      - media_volume_lo:/home/app/beckend/media

    depends_on:
      - redis
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_lo:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user_lo
      - POSTGRES_PASSWORD=1234_lo
      - POSTGRES_DB=adora_db_lo
      - POSTGRES_INITDB_ARGS:'--encoding=UTF-8'

    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: adora-app
    
    entrypoint: ./docker-entrypoint-celery-worker.sh
    # volumes:
    #   - .:/home/app/backend/
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_ENV=development
    depends_on:
      - redis
      - db
      - backend

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: adora-app
  #   entrypoint: ./docker-entrypoint-celery-beat.sh
  #   # volumes:
  #   #   - .:/home/app/backend/
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - redis
  #     - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: adora-app
    entrypoint: ./docker-entrypoint-celery-flower.sh
    volumes:
      - static_volume_lo:/home/app/backend/core/static
    env_file:
      - ./.env.dev

    environment:
      - DJANGO_ENV=development
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

    # restart: unless-stopped
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume_lo:/home/app/beckend/core/staticfiles
  #   ports:
  #     - 80:8000
  #   depends_on:
  #     - backend

volumes:
  static_volume_lo:
  postgres_data_lo:
  media_volume_lo:

