version: "3.8"

services:
  backend:
    build: .
    # command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

    environment:
      - DJANGO_ENV=development
    
    volumes:
      - .:/home/app/backend/
      - static_volume:/home/app/beckend/core/staticfiles
      - media_volume:/home/app/beckend/media

    depends_on:
      - redis
      - db

  db: 
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=adora_db
      - POSTGRES_INITDB_ARGS:'--encoding=UTF-8'

    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/beckend/core/staticfiles
    ports:
      - 80:8000
    depends_on:
      - backend

volumes:
  static_volume:
  postgres_data:
  media_volume:
