version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: adora-app
    # command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

    environment:
      - DJANGO_ENV=development

    volumes:
      - .:/home/app/backend/
      - static_volume_lo:/home/app/beckend/core/staticfiles
      - media_volume_lo:/home/app/beckend/media

    depends_on:
      - redis_master
      - redis_replica
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_lo:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adora_user_lo
      - POSTGRES_PASSWORD=1234_lo
      - POSTGRES_DB=adora_db_lo
      - POSTGRES_INITDB_ARGS:'--encoding=UTF-8'

    ports:
      - 5432:5432


  celery:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: adora-app
    user: "1000:1000"
    
    entrypoint: ./docker-entrypoint-celery-worker.sh
    # volumes:
    #   - .:/home/app/backend/
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_ENV=development
    depends_on:
      - redis_master
      - redis_replica
      - db
      - backend

  redis_master:
    image: "redis:alpine"
    container_name: redis_master
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
    command: redis-server --requirepass "1234"  # Optional: If you want to set a password
    restart: always

  redis_replica:
    image: "redis:alpine"
    container_name: redis_replica
    environment:
      - REDIS_MASTER_HOST=redis_master
      - REDIS_MASTER_PORT=6379
    command: redis-server --slaveof redis_master 6379 --requirepass "1234" --masterauth "1234"  # Optional: if using password
    ports:
      - "6380:6379"  # Map to a different port to avoid conflict
    restart: always
  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: adora-app
  #   entrypoint: ./docker-entrypoint-celery-beat.sh
  #   # volumes:
  #   #   - .:/home/app/backend/
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - redis
      # - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: adora-app
    entrypoint: ./docker-entrypoint-celery-flower.sh
    volumes:
      - static_volume_lo:/home/app/backend/core/static
    env_file:
      - ./.env.dev

    environment:
      - DJANGO_ENV=development
      - REDIS_PASSWORD="1234"
    ports:
      - 5557:5555
    depends_on:
      - redis_master
      - db

    restart: unless-stopped
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume_lo:/home/app/beckend/core/staticfiles
  #   ports:
  #     - 80:8000
  #   depends_on:
  #     - backend
  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_usr
      WORDPRESS_DB_PASSWORD: wusr@2025@66688
    volumes:
      - wordpress_data:/var/www/html
    # expose:
    #   - "80"
    depends_on:
      - wordpress_db
        # condition: service_healthy
    
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/wp-login.php"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
      
  wordpress_db:
      image: mysql:8.0
      container_name: wordpress_db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: wp_db
        MYSQL_USER: wp_usr
        MYSQL_PASSWORD: wusr@2025@66688
        MYSQL_ROOT_PASSWORD: rootpass
      volumes:
        - wordpress_db_data:/var/lib/mysql

      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wp_usr", "-p", "wusr@2025@66688"]
        interval: 5s
        timeout: 5s
        retries: 5

      
  # wordpress:
  #   image: wordpress:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     WORDPRESS_DB_HOST: wordpress_db:3306
  #     WORDPRESS_DB_USER: adora_user_lo
  #     WORDPRESS_DB_PASSWORD: 1234_lo
  #     WORDPRESS_DB_NAME: adora_db_lo
  #   depends_on:
  #     - wordpress_db

  # wordpress_db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: adora_db_lo
  #     MYSQL_USER: adora_user_lo
  #     MYSQL_PASSWORD: 1234_lo
  #   volumes:
  #     - ./wordpress_db_data:/var/lib/mysql


volumes:
  static_volume_lo:
  postgres_data_lo:
  media_volume_lo:
  redis_master_data:
  wordpress_data:
  wordpress_db_data: